### ISSUE TITLE
Character's guild can be null

### ISSUE THREAD

**Issue by Northburns** [Kryszak/gwatlin#104]
https://github.com/Kryszak/gwatlin/blob/46f017c3ca3eed86098a8bd69c573519e76d7b10/src/main/kotlin/io/github/kryszak/gwatlin/api/characters/model/Character.kt#L20

Character's guild property is optional, [API docs @ gw2 wiki](https://wiki.guildwars2.com/wiki/API:2/characters#Core). The Character class above doesn't allow null values to guild property, resulting in the following error output.

```
[main] ERROR io.github.kryszak.gwatlin.http.BaseHttpClient - Request failed! Unexpected JSON token at offset 146: Unexpected 'null' value instead of string literal at path: $.guild
JSON input: .....  "level": 80,
  "guild": null,
  "age": 476620,
  "last_mod.....
Exception in thread "main" The input has already been written to an output stream and can not be consumed again.
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap$default(FuelError.kt:83)
Caused by: java.lang.IllegalStateException: The input has already been written to an output stream and can not be consumed again.
	com.github.kittinunf.fuel.core.requests.DefaultBody$Companion$CONSUMED_STREAM$1.invoke(DefaultBody.kt:125)
	com.github.kittinunf.fuel.core.requests.DefaultBody$Companion$CONSUMED_STREAM$1.invoke(DefaultBody.kt:119)
	com.github.kittinunf.fuel.core.requests.DefaultBody.writeTo(DefaultBody.kt:84)
	com.github.kittinunf.fuel.core.requests.DefaultBody.toByteArray(DefaultBody.kt:50)
	com.github.kittinunf.fuel.core.Response.getData(Response.kt:32)
	io.github.kryszak.gwatlin.http.BaseHttpClient.processResult(BaseHttpClient.kt:67)
	io.github.kryszak.gwatlin.http.BaseHttpClient.access$processResult(BaseHttpClient.kt:16)
	io.github.kryszak.gwatlin.clients.characters.CharactersClient.getCharacter(CharactersClient.kt:147)
	io.github.kryszak.gwatlin.api.characters.GWCharactersClient.getCharacter(GWCharactersClient.kt:24)
	northburns.gw2.Application1$main$1.invokeSuspend(Application1.kt:25)
	kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	northburns.gw2.Application1.main(Application1.kt:12)

	at com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:86)
	at com.github.kittinunf.fuel.core.FuelError$Companion.wrap$default(FuelError.kt:83)
Caused by: java.lang.IllegalStateException: The input has already been written to an output stream and can not be consumed again.
	at com.github.kittinunf.fuel.core.requests.DefaultBody$Companion$CONSUMED_STREAM$1.invoke(DefaultBody.kt:125)
	at com.github.kittinunf.fuel.core.requests.DefaultBody$Companion$CONSUMED_STREAM$1.invoke(DefaultBody.kt:119)
	at com.github.kittinunf.fuel.core.requests.DefaultBody.writeTo(DefaultBody.kt:84)
	at com.github.kittinunf.fuel.core.requests.DefaultBody.toByteArray(DefaultBody.kt:50)
	at com.github.kittinunf.fuel.core.Response.getData(Response.kt:32)
	at io.github.kryszak.gwatlin.http.BaseHttpClient.processResult(BaseHttpClient.kt:67)
	at io.github.kryszak.gwatlin.http.BaseHttpClient.access$processResult(BaseHttpClient.kt:16)
	at io.github.kryszak.gwatlin.clients.characters.CharactersClient.getCharacter(CharactersClient.kt:147)
	at io.github.kryszak.gwatlin.api.characters.GWCharactersClient.getCharacter(GWCharactersClient.kt:24)
	at northburns.gw2.Application1$main$1.invokeSuspend(Application1.kt:25)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at northburns.gw2.Application1.main(Application1.kt:12)
```

Sidenote: I know, I know, I should join a guild. I haven't played for very long yet 🙈

**Comment by Kryszak** [comment]
Fix released in version 1.9.6
